version: '3.8'
services:
  # api1: &api # API - Instância 01
  #   image: jorgehrique/rinha-backend-java:0.0.1
  #   container_name: api1
  #   depends_on:
  #     - db
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: '125M'

  # api2: # API - Instância 02
  #   <<: *api 
  #   container_name: api2

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # depends_on:
    #   - api1
    #   - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '50M'

  mongo: # Banco de dados
    image: mongo:7.0.5-jammy
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '200M'

  # database-client: # Debug only - Cliente Banco de dados
  #   image: mongo-express:1.0.2-20-alpine3.19
  #   container_name: database-client
  #   environment:
  #     ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongo:27017/
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: user
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: pass
  #   depends_on:
  #     - mongo
