@rinha_app_HostAddress = http://localhost:9999

### Create a new transaction
POST {{rinha_app_HostAddress}}/clientes/6/transacoes
Content-Type: application/json

{
    "valor": 901,
    "tipo": "d",
    "descricao": "pix"
}

### GET Extrato
GET {{rinha_app_HostAddress}}/clientes/1/extrato
Content-Type: application/json