@rinha_app_HostAddress = http://localhost:9999

### Create a new transaction
POST {{rinha_app_HostAddress}}/clientes/1/transacoes
Content-Type: application/json

{
    "valor": 1,
    "tipo": "c",
    "descricao": "aa"
}

### GET Extrato
GET {{rinha_app_HostAddress}}/clientes/1/extrato
Content-Type: application/json